services:
  jobmanager:
    image: flink:1.18-scala_2.12
    container_name: flink-jobmanager
    hostname: jobmanager
    ports:
      - "8081:8081"   # Flink Web UI
      - "6123:6123"   # RPC port
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.rpc.port: 6123
        jobmanager.bind-host: 0.0.0.0
        rest.address: jobmanager
        rest.bind-address: 0.0.0.0
        jobmanager.memory.process.size: 1600m
        parallelism.default: 2
    networks:
      - double-slash-net
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8081/overview > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
    - ./jars:/opt/flink/lib

  taskmanager:
    image: flink:1.18-scala_2.12
    container_name: flink-taskmanager
    hostname: taskmanager
    depends_on:
      jobmanager:
        condition: service_healthy
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.rpc.port: 6123
        taskmanager.bind-host: 0.0.0.0
        taskmanager.host: taskmanager
        taskmanager.memory.process.size: 1728m
        taskmanager.numberOfTaskSlots: 4
        parallelism.default: 2
    networks:
      - double-slash-net
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://jobmanager:8081/taskmanagers > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

networks:
  double-slash-net:
    name: double-slash-net
    driver: bridge
